### ISSUE TITLE
Duplicate requires in app.js

### ISSUE THREAD

**Issue by finnhodgkin** [fac-12/upShop#48]
Minor issue but in app.js you're [requiring both `./controllers` and `./controllers/index`](https://github.com/fac-12/upShop/blob/master/src/app.js#L6-L12). Node checks for an `index.js` file if you pass a directory instead of a file (`./controllers`). Remove one of the `require`s and `.use`s (probably keep 'controller' to match the directory name).

**Comment by njseeto** [comment]
File changed 👍
