### ISSUE TITLE
Fix lint rules to suit your setup

### ISSUE THREAD

**Issue by finnhodgkin** [fac-12/upShop#49]
There are quite a lot of lint errors/warnings in your project that are just ignored. If you find yourself doing this a lot or if you don't agree with a lint rule, I'd advise just removing it from your `eslintrc.json` rather than having an error-filled text editor. For example `no-shadow`:

```json
{
  "extends": "airbnb-base",
  "rules": {
    "no-shadow": 0
  }
}
```

**Comment by njseeto** [comment]
Thanks for the tip 👍 🙌
